---
- name: Implementing host scope variables
  hosts: 172.31.30.148
  tasks:
    - name: Create usrrs
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
        comment: "{{e}}"
        shell: "{{f}}"
