- name: Create a user on all the servers
  hosts: all
  serial: 1
  tasks:
    - name: User creation
      user:
        name: Ravi
        password: intelliqit
        uid: 2222
        home: /tmp/Ravi
        shell: /bin/bash
        comment: "Super user"
...
