---
- name: Install/uninstall/upgrade s/w apps
  hosts: all
  tasks:
    - name: Install/install or upgrade
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: present,c: no}
        - {a: git,b: absent,c: no}
        - {a: maven,b: latest,c: yes}
